keys:
  - &primary age1pqr4uyzrsnm0l5tgtgy09x76xdtar2ex9pq6z3muw9p38z6v59nskel73t
  - &laptop age1kx30ua2qdu6ug0qdvxun54hjmlajt9esd9tsnmjjuyxwt7q5a3vsvgvk75
  - &desktop age1dsvv2wangclezl745vqlvvmcggaszc4fcxu84ks7qphm5tupq98srdtgx8
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - age:
      - *primary
      - *laptop
      - *desktop
